[www]
user = www-data
group = www-data

listen = 9000

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; 보안: .php 확장자만 허용
security.limit_extensions = .php

; 워커 로그 캡처
catch_workers_output = yes
decorate_workers_output = no
